'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CLEVIR_INCA_7_2.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property cropped_image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cropped image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property cropped_image_60() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cropped image 60", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property green_vehicle_ahead() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("green vehicle ahead", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mic_50() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mic 50", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mic_50_Green() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mic 50 Green", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property mic_50_Red() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("mic 50 Red", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property orange_ped() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("orange ped", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property orange_vehicle_ahead() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("orange vehicle ahead", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_eject_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-media-eject[1]", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_playback_pause_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-media-playback-pause[1]", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_playback_start_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-media-playback-start[1]", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_playback_stop_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-media-playback-stop[1]", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_skip_backward_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-media-skip-backward[1]", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_skip_forward_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-media-skip-forward[1]", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Oxygen_Icons1() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Oxygen-Icons1", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Red_Ped() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Red Ped", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property red_vehicle_ahead() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("red vehicle ahead", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Saki_NuoveXT_Actions_folder_file_import_1_() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Saki-NuoveXT-Actions-folder-file-import[1]", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
