'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CLEVIR_INCA_7_5.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueLeftArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueLeftArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueRightArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueRightArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cropped_image_60() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cropped_image_60", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GrayLeftArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GrayLeftArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GrayRightArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GrayRightArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green_vehicle_ahead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_vehicle_ahead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenLeftArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenLeftArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenRightArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenRightArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mic_50_Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mic_50_Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mic_50_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mic_50_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orange_ped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orange_ped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orange_vehicle_ahead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orange_vehicle_ahead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_eject_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_eject_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_playback_pause_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_playback_pause_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_playback_start_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_playback_start_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_playback_stop_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_playback_stop_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_seek_backward_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_seek_backward_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_seek_forward_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_seek_forward_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_skip_backward_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_skip_backward_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Oxygen_Icons_org_Oxygen_Actions_media_skip_forward_1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Oxygen_Icons_org_Oxygen_Actions_media_skip_forward_1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Red_Ped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red_Ped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property red_vehicle_ahead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_vehicle_ahead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedLeftArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedLeftArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedRightArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedRightArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowLeftArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowLeftArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowRightArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowRightArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
